import {contours,geoPath,geoTransform} from 'd3';
const CELL=3.2,LEVELS=[.1,.22,.34,.46,.58,.7,.82];
type Bounds=[[number,number],[number,number]];type TerrainMemory={id:string;importance:number|null};
export interface Terrain {levels:{v:number;d:string}[];pts:Record<string,[number,number]>;summits:{id:string;xy:[number,number]}[]}
type Raster={nx:number;ny:number;x0:number;y0:number;mask:Uint8Array;dist:Float32Array;land:number[]};
const rcache=new Map<string,Raster>(),tcache=new Map<string,Terrain>();
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0};
const rng=(seed:number)=>{let s=seed||1;return()=>{s=(s*1103515245+12345)&0x7fffffff;return s/0x7fffffff}};
function raster(id:string,d:string,b:Bounds):Raster{const key=id+'|'+d.length+'|'+b[0][0].toFixed(1);const cached=rcache.get(key);if(cached)return cached;const x0=b[0][0]-CELL*2,y0=b[0][1]-CELL*2,nx=Math.ceil((b[1][0]-b[0][0])/CELL)+4,ny=Math.ceil((b[1][1]-b[0][1])/CELL)+4;const c=document.createElement('canvas');c.width=nx;c.height=ny;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');ctx.scale(1/CELL,1/CELL);ctx.translate(-x0,-y0);ctx.fillStyle='#000';ctx.fill(new Path2D(d));const img=ctx.getImageData(0,0,nx,ny).data,mask=new Uint8Array(nx*ny);for(let i=0;i<nx*ny;i++)mask[i]=img[i*4+3]>100?1:0;const dist=new Float32Array(nx*ny);for(let y=0;y<ny;y++)for(let x=0;x<nx;x++){const i=y*nx+x;if(!mask[i])continue;if(x===0||y===0){dist[i]=1;continue}dist[i]=Math.min(dist[i-1]+1,dist[i-nx]+1,dist[i-nx-1]+1.4,(x<nx-1?dist[i-nx+1]:0)+1.4)}for(let y=ny-1;y>=0;y--)for(let x=nx-1;x>=0;x--){const i=y*nx+x;if(!mask[i])continue;if(x===nx-1||y===ny-1){dist[i]=Math.min(dist[i],1);continue}dist[i]=Math.min(dist[i],dist[i+1]+1,dist[i+nx]+1,dist[i+nx+1]+1.4,(x>0?dist[i+nx-1]:0)+1.4)}const land:number[]=[];for(let i=0;i<nx*ny;i++)if(mask[i]&&dist[i]>=1.5)land.push(i);if(!land.length)for(let i=0;i<nx*ny;i++)if(mask[i])land.push(i);const value={nx,ny,x0,y0,mask,dist,land};rcache.set(key,value);return value}
export function buildTerrain(id:string,d:string,b:Bounds,mems:TerrainMemory[],sigmaPx:number):Terrain{const key=id+'|'+d.length+'|'+mems.map(m=>m.id+':'+(m.importance||'')).join(',');const cached=tcache.get(key);if(cached)return cached;const r=raster(id,d,b),{nx,ny,mask,dist,land}=r,sig=sigmaPx/CELL,pts:{m:TerrainMemory;p:[number,number]}[]=[],placed:[number,number][]=[];mems.forEach(m=>{const rnd=rng(hash(id+m.id));let p:[number,number]|null=null;if(placed.length&&rnd()<.6)for(let t=0;t<14&&!p;t++){const a=placed[Math.floor(rnd()*placed.length)],ang=rnd()*6.2832,rad=(rnd()+rnd())*sig*1.1,x=Math.round(a[0]+Math.cos(ang)*rad),y=Math.round(a[1]+Math.sin(ang)*rad);if(x>=0&&y>=0&&x<nx&&y<ny&&mask[y*nx+x]&&dist[y*nx+x]>=1.5)p=[x,y]}if(!p){const i=land[Math.floor(rnd()*land.length)];p=[i%nx,Math.floor(i/nx)]}placed.push(p);pts.push({m,p})});const E=new Float32Array(nx*ny);pts.forEach(({m,p})=>{const imp=m.importance||2.5,w=.3+.55*imp/5,s=sig*(.7+.6*imp/5),R=Math.ceil(s*3);for(let y=Math.max(0,p[1]-R);y<=Math.min(ny-1,p[1]+R);y++)for(let x=Math.max(0,p[0]-R);x<=Math.min(nx-1,p[0]+R);x++){const i=y*nx+x;if(!mask[i])continue;const dx=x-p[0],dy=y-p[1];E[i]+=w*Math.exp(-(dx*dx+dy*dy)/(2*s*s))}});const V=new Float32Array(nx*ny);for(let i=0;i<nx*ny;i++)if(mask[i])V[i]=(1-Math.exp(-E[i]/1.6))*Math.min(1,dist[i]/2.5);const tf=geoPath(geoTransform({point(x,y){this.stream.point(r.x0+x*CELL,r.y0+y*CELL)}}));const levels=mems.length?contours().size([nx,ny]).thresholds(LEVELS).smooth(true)(Array.from(V)).map(c=>({v:c.value,d:tf(c) as string})).filter(c=>c.d):[];const px=(p:[number,number]):[number,number]=>[r.x0+(p[0]+.5)*CELL,r.y0+(p[1]+.5)*CELL],ptMap:Record<string,[number,number]>={};pts.forEach(({m,p})=>ptMap[m.id]=px(p));const summits=pts.filter(x=>(x.m.importance||0)>=5).sort((a,b)=>V[b.p[1]*nx+b.p[0]]-V[a.p[1]*nx+a.p[0]]).slice(0,3).map(x=>({id:x.m.id,xy:px(x.p)}));const out={levels,pts:ptMap,summits};tcache.set(key,out);return out}
